CREATE TABLE public.account_items (id uuid DEFAULT gen_random_uuid() NOT NULL, group_name character varying(100) NOT NULL, item_name character varying(100) NOT NULL, value_type character varying(20) NOT NULL, sort_order integer DEFAULT 0, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.account_items ADD CONSTRAINT account_items_group_name_item_name_key UNIQUE (group_name, item_name);
ALTER TABLE public.account_items ADD CONSTRAINT account_items_pkey PRIMARY KEY (id);
ALTER TABLE public.account_items ADD CONSTRAINT account_items_value_type_check CHECK (value_type::text = ANY (ARRAY['CURRENCY'::character varying, 'PERCENTAGE'::character varying, 'BOTH'::character varying]::text[]));
ALTER TABLE public.account_items ADD CONSTRAINT uq_account_group_item UNIQUE (group_name, item_name);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.account_items TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.account_items TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.account_items TO service_role;
CREATE TABLE public.projection_details (id uuid DEFAULT gen_random_uuid() NOT NULL, projection_header_id uuid NOT NULL, account_item_id uuid NOT NULL, amount_usd numeric(14,2) DEFAULT 0.00, percentage numeric(6,4) DEFAULT 0.0000, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.projection_details ADD CONSTRAINT projection_details_account_item_id_fkey FOREIGN KEY (account_item_id) REFERENCES public.account_items(id);
ALTER TABLE public.projection_details ADD CONSTRAINT projection_details_pkey PRIMARY KEY (id);
ALTER TABLE public.projection_details ADD CONSTRAINT projection_details_projection_header_id_account_item_id_key UNIQUE (projection_header_id, account_item_id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.projection_details TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.projection_details TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.projection_details TO service_role;
CREATE TABLE public.projection_headers (id uuid DEFAULT gen_random_uuid() NOT NULL, store_id uuid NOT NULL, period_year integer NOT NULL, period_month integer NOT NULL, scenario character varying(50) DEFAULT 'BASE'::character varying, total_sales_net numeric(14,2) DEFAULT 0.00, result_before_depreciation numeric(14,2) DEFAULT 0.00, created_by uuid, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.projection_headers ADD CONSTRAINT projection_headers_period_month_check CHECK (period_month >= 1 AND period_month <= 12);
ALTER TABLE public.projection_headers ADD CONSTRAINT projection_headers_period_year_check CHECK (period_year >= 2020);
ALTER TABLE public.projection_headers ADD CONSTRAINT projection_headers_pkey PRIMARY KEY (id);
ALTER TABLE public.projection_details ADD CONSTRAINT projection_details_projection_header_id_fkey FOREIGN KEY (projection_header_id) REFERENCES public.projection_headers(id) ON DELETE CASCADE;
ALTER TABLE public.projection_headers ADD CONSTRAINT projection_headers_store_id_period_year_period_month_scenar_key UNIQUE (store_id, period_year, period_month, scenario);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.projection_headers TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.projection_headers TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.projection_headers TO service_role;
CREATE TABLE public.stores (id uuid DEFAULT gen_random_uuid() NOT NULL, code character varying(20) NOT NULL, name character varying(100) NOT NULL, is_active boolean DEFAULT true, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.stores ADD CONSTRAINT stores_code_key UNIQUE (code);
ALTER TABLE public.stores ADD CONSTRAINT stores_pkey PRIMARY KEY (id);
ALTER TABLE public.projection_headers ADD CONSTRAINT projection_headers_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.stores TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.stores TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.stores TO service_role;
